# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Instalar node
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - name: Subir artefacto
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./dist
  deploy:
      environment:
        name: github-pages
        url: https://www.teinvite.ar  # Tu dominio personalizado
      needs: build  # Ejecuta el trabajo de despliegue después del build
      runs-on: ubuntu-latest
      steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
